# Generated by Django 3.2.4 on 2021-06-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Student',
        ),
    ]
