# Generated by Django 3.2 on 2021-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210504_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(default='', max_length=50)),
                ('contact_phone', models.CharField(default='', max_length=70)),
                ('contact_desciption', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
