# Generated by Django 3.2.5 on 2021-07-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0002_events_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_thumbnail',
            field=models.ImageField(default='', upload_to='events_app/images'),
        ),
    ]
