# Generated by Django 3.2.5 on 2021-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0006_alter_events_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(max_length=150),
        ),
    ]
