# Generated by Django 3.2.5 on 2021-07-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0008_alter_events_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_title',
            new_name='title',
        ),
    ]
