# Generated by Django 3.2.5 on 2021-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0009_auto_20210706_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='event_date',
        ),
    ]
