# Generated by Django 3.2.5 on 2021-07-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0010_rename_date_events_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='id',
            new_name='event_id',
        ),
    ]
