# Generated by Django 3.2.5 on 2021-07-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0011_rename_id_events_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
    ]
