# Generated by Django 3.2.5 on 2021-07-07 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0012_remove_events_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
