# Generated by Django 3.2.5 on 2021-07-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
