# Generated by Django 3.2.5 on 2021-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0017_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gadgets', 'Gadgets'), ('food', 'Food'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('study', 'Study'), ('session', 'Session')], default='', max_length=50),
        ),
    ]
