# Generated by Django 3.2.5 on 2021-07-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0020_auto_20210720_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='events_app/event_thumbnail'),
        ),
    ]
