# Generated by Django 3.2.5 on 2021-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_app', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default='default.jpg', upload_to='events_app/author_profile_img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='events_app/author_profile_img'),
        ),
    ]
