# Generated by Django 3.2.2 on 2021-05-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
