# Generated by Django 3.2.2 on 2021-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
    ]
