# Generated by Django 3.2.5 on 2021-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_address',
            field=models.CharField(default='', max_length=70),
        ),
    ]
