# Generated by Django 3.2.6 on 2021-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_auto_20210905_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa'), ('PayPal', 'PayPal')], default='Cash on delivery', max_length=20),
        ),
    ]
