# Generated by Django 3.2.5 on 2021-08-31 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('interest_obj', models.ManyToManyField(to='CustomeApp1.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='PersonStreetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('city_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomeApp1.city')),
                ('person_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CustomeApp1.person')),
            ],
        ),
    ]
