# Generated by Django 3.2.5 on 2021-09-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomeApp1', '0002_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='CustomeApp1.department'),
        ),
    ]
